[package]
name = "fc"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
anyhow = "1.0.79"
binary = { version = "0.1.0", path = "binary" }
image = "0.24.7"
macroquad = "0.4.4"
winit = "0.29.9"
