mod opecode;
mod operand;

pub use opecode::Opecode;
pub use operand::{IndexRegister, Operand};

pub const ORDER_SET: [[(Opecode, Operand); 16]; 16] = [
    /*0*/
    [
        (Opecode::BRK, Operand::Implied),
        (Opecode::ORA, Operand::IndirectIndex(IndexRegister::X)),
        (Opecode::NOP, Operand::Nope),
        (Opecode::NOP, Operand::Nope),
        (Opecode::NOP, Operand::Nope),
        (Opecode::ORA, Operand::ZeroPage),
        (Opecode::ASL, Operand::ZeroPage),
        (Opecode::NOP, Operand::Nope),
        (Opecode::PHP, Operand::Implied),
        (Opecode::ORA, Operand::Immediate),
        (Opecode::ASL, Operand::Accumulator),
        (Opecode::NOP, Operand::Nope),
        (Opecode::NOP, Operand::Nope),
        (Opecode::ORA, Operand::Absolute),
        (Opecode::ASL, Operand::Absolute),
        (Opecode::NOP, Operand::Nope),
    ],
    /*1*/
    [
        (Opecode::BPL, Operand::Relative),
        (Opecode::ORA, Operand::IndirectIndex(IndexRegister::Y)),
        (Opecode::NOP, Operand::Nope),
        (Opecode::NOP, Operand::Nope),
        (Opecode::NOP, Operand::Nope),
        (Opecode::ORA, Operand::ZeroPageIndex(IndexRegister::X)),
        (Opecode::ASL, Operand::ZeroPageIndex(IndexRegister::X)),
        (Opecode::NOP, Operand::Nope),
        (Opecode::CLC, Operand::Implied),
        (Opecode::ORA, Operand::AbsoluteIndex(IndexRegister::Y)),
        (Opecode::NOP, Operand::Nope),
        (Opecode::NOP, Operand::Nope),
        (Opecode::NOP, Operand::Nope),
        (Opecode::ORA, Operand::AbsoluteIndex(IndexRegister::X)),
        (Opecode::ASL, Operand::AbsoluteIndex(IndexRegister::X)),
        (Opecode::NOP, Operand::Nope),
    ],
    /*2*/
    [
        (Opecode::JSR, Operand::Absolute),
        (Opecode::AND, Operand::IndirectIndex(IndexRegister::X)),
        (Opecode::NOP, Operand::Nope),
        (Opecode::NOP, Operand::Nope),
        (Opecode::BIT, Operand::ZeroPage),
        (Opecode::AND, Operand::ZeroPage),
        (Opecode::ROL, Operand::ZeroPage),
        (Opecode::NOP, Operand::Nope),
        (Opecode::PLP, Operand::Implied),
        (Opecode::AND, Operand::Immediate),
        (Opecode::ROL, Operand::Accumulator),
        (Opecode::NOP, Operand::Nope),
        (Opecode::BIT, Operand::Absolute),
        (Opecode::AND, Operand::Absolute),
        (Opecode::ROL, Operand::Absolute),
        (Opecode::NOP, Operand::Nope),
    ],
    /*3*/
    [
        (Opecode::BMI, Operand::Relative),
        (Opecode::AND, Operand::IndirectIndex(IndexRegister::Y)),
        (Opecode::NOP, Operand::Nope),
        (Opecode::NOP, Operand::Nope),
        (Opecode::NOP, Operand::Nope),
        (Opecode::AND, Operand::ZeroPageIndex(IndexRegister::X)),
        (Opecode::ROL, Operand::ZeroPageIndex(IndexRegister::X)),
        (Opecode::NOP, Operand::Nope),
        (Opecode::SEC, Operand::Implied),
        (Opecode::AND, Operand::AbsoluteIndex(IndexRegister::Y)),
        (Opecode::NOP, Operand::Nope),
        (Opecode::NOP, Operand::Nope),
        (Opecode::NOP, Operand::Nope),
        (Opecode::AND, Operand::AbsoluteIndex(IndexRegister::X)),
        (Opecode::ROL, Operand::AbsoluteIndex(IndexRegister::X)),
        (Opecode::NOP, Operand::Nope),
    ],
    /*4*/
    [
        (Opecode::RTI, Operand::Implied),
        (Opecode::EOR, Operand::IndirectIndex(IndexRegister::X)),
        (Opecode::NOP, Operand::Nope),
        (Opecode::NOP, Operand::Nope),
        (Opecode::NOP, Operand::Nope),
        (Opecode::EOR, Operand::ZeroPage),
        (Opecode::LSR, Operand::ZeroPage),
        (Opecode::NOP, Operand::Nope),
        (Opecode::PHA, Operand::Implied),
        (Opecode::EOR, Operand::Immediate),
        (Opecode::LSR, Operand::Accumulator),
        (Opecode::NOP, Operand::Nope),
        (Opecode::JMP, Operand::Absolute),
        (Opecode::EOR, Operand::Absolute),
        (Opecode::LSR, Operand::Absolute),
        (Opecode::NOP, Operand::Nope),
    ],
    /*5*/
    [
        (Opecode::BVC, Operand::Relative),
        (Opecode::EOR, Operand::IndirectIndex(IndexRegister::Y)),
        (Opecode::NOP, Operand::Nope),
        (Opecode::NOP, Operand::Nope),
        (Opecode::NOP, Operand::Nope),
        (Opecode::EOR, Operand::ZeroPageIndex(IndexRegister::X)),
        (Opecode::LSR, Operand::ZeroPageIndex(IndexRegister::X)),
        (Opecode::NOP, Operand::Nope),
        (Opecode::CLI, Operand::Implied),
        (Opecode::EOR, Operand::AbsoluteIndex(IndexRegister::Y)),
        (Opecode::NOP, Operand::Nope),
        (Opecode::NOP, Operand::Nope),
        (Opecode::NOP, Operand::Nope),
        (Opecode::EOR, Operand::AbsoluteIndex(IndexRegister::X)),
        (Opecode::LSR, Operand::AbsoluteIndex(IndexRegister::X)),
        (Opecode::NOP, Operand::Nope),
    ],
    /*6*/
    [
        (Opecode::RTS, Operand::Implied),
        (Opecode::ADC, Operand::IndirectIndex(IndexRegister::X)),
        (Opecode::NOP, Operand::Nope),
        (Opecode::NOP, Operand::Nope),
        (Opecode::NOP, Operand::Nope),
        (Opecode::ADC, Operand::ZeroPage),
        (Opecode::ROR, Operand::ZeroPage),
        (Opecode::NOP, Operand::Nope),
        (Opecode::PLA, Operand::Implied),
        (Opecode::ADC, Operand::Immediate),
        (Opecode::ROR, Operand::Accumulator),
        (Opecode::NOP, Operand::Nope),
        (Opecode::JMP, Operand::AbsoluteIndirect),
        (Opecode::ADC, Operand::Absolute),
        (Opecode::ROR, Operand::Absolute),
        (Opecode::NOP, Operand::Nope),
    ],
    /*7*/
    [
        (Opecode::BVS, Operand::Relative),
        (Opecode::ADC, Operand::IndirectIndex(IndexRegister::Y)),
        (Opecode::NOP, Operand::Nope),
        (Opecode::NOP, Operand::Nope),
        (Opecode::NOP, Operand::Nope),
        (Opecode::ADC, Operand::ZeroPageIndex(IndexRegister::X)),
        (Opecode::ROR, Operand::ZeroPageIndex(IndexRegister::X)),
        (Opecode::NOP, Operand::Nope),
        (Opecode::SEI, Operand::Implied),
        (Opecode::ADC, Operand::AbsoluteIndex(IndexRegister::Y)),
        (Opecode::NOP, Operand::Nope),
        (Opecode::NOP, Operand::Nope),
        (Opecode::NOP, Operand::Nope),
        (Opecode::ADC, Operand::AbsoluteIndex(IndexRegister::X)),
        (Opecode::ROR, Operand::AbsoluteIndex(IndexRegister::X)),
        (Opecode::NOP, Operand::Nope),
    ],
    /*8*/
    [
        (Opecode::NOP, Operand::Nope),
        (Opecode::STA, Operand::IndirectIndex(IndexRegister::X)),
        (Opecode::NOP, Operand::Nope),
        (Opecode::NOP, Operand::Nope),
        (Opecode::STY, Operand::ZeroPage),
        (Opecode::STA, Operand::ZeroPage),
        (Opecode::STX, Operand::ZeroPage),
        (Opecode::NOP, Operand::Nope),
        (Opecode::DEY, Operand::Implied),
        (Opecode::NOP, Operand::Nope),
        (Opecode::TXA, Operand::Implied),
        (Opecode::NOP, Operand::Nope),
        (Opecode::STY, Operand::Absolute),
        (Opecode::STA, Operand::Absolute),
        (Opecode::STX, Operand::Absolute),
        (Opecode::NOP, Operand::Nope),
    ],
    /*9*/
    [
        (Opecode::BCC, Operand::Relative),
        (Opecode::STA, Operand::IndirectIndex(IndexRegister::Y)),
        (Opecode::NOP, Operand::Nope),
        (Opecode::NOP, Operand::Nope),
        (Opecode::STY, Operand::ZeroPageIndex(IndexRegister::X)),
        (Opecode::STA, Operand::ZeroPageIndex(IndexRegister::X)),
        (Opecode::STX, Operand::ZeroPageIndex(IndexRegister::Y)),
        (Opecode::NOP, Operand::Nope),
        (Opecode::TYA, Operand::Implied),
        (Opecode::STA, Operand::AbsoluteIndex(IndexRegister::Y)),
        (Opecode::TXS, Operand::Implied),
        (Opecode::NOP, Operand::Nope),
        (Opecode::NOP, Operand::Nope),
        (Opecode::STA, Operand::AbsoluteIndex(IndexRegister::X)),
        (Opecode::NOP, Operand::Nope),
        (Opecode::NOP, Operand::Nope),
    ],
    /*a*/
    [
        (Opecode::LDY, Operand::Immediate),
        (Opecode::LDA, Operand::IndirectIndex(IndexRegister::X)),
        (Opecode::LDX, Operand::Immediate),
        (Opecode::NOP, Operand::Nope),
        (Opecode::LDY, Operand::ZeroPage),
        (Opecode::LDA, Operand::ZeroPage),
        (Opecode::LDX, Operand::ZeroPage),
        (Opecode::NOP, Operand::Nope),
        (Opecode::TAY, Operand::Implied),
        (Opecode::LDA, Operand::Immediate),
        (Opecode::TAX, Operand::Implied),
        (Opecode::NOP, Operand::Nope),
        (Opecode::LDY, Operand::Absolute),
        (Opecode::LDA, Operand::Absolute),
        (Opecode::LDX, Operand::Absolute),
        (Opecode::NOP, Operand::Nope),
    ],
    /*b*/
    [
        (Opecode::BCS, Operand::Relative),
        (Opecode::LDA, Operand::IndirectIndex(IndexRegister::Y)),
        (Opecode::NOP, Operand::Nope),
        (Opecode::NOP, Operand::Nope),
        (Opecode::LDY, Operand::ZeroPageIndex(IndexRegister::X)),
        (Opecode::LDA, Operand::ZeroPageIndex(IndexRegister::X)),
        (Opecode::LDX, Operand::ZeroPageIndex(IndexRegister::X)),
        (Opecode::NOP, Operand::Nope),
        (Opecode::CLV, Operand::Implied),
        (Opecode::LDA, Operand::AbsoluteIndex(IndexRegister::Y)),
        (Opecode::TSX, Operand::Implied),
        (Opecode::NOP, Operand::Nope),
        (Opecode::LDY, Operand::AbsoluteIndex(IndexRegister::X)),
        (Opecode::LDA, Operand::AbsoluteIndex(IndexRegister::X)),
        (Opecode::LDX, Operand::AbsoluteIndex(IndexRegister::Y)),
        (Opecode::NOP, Operand::Nope),
    ],
    /*c*/
    [
        (Opecode::CPY, Operand::Immediate),
        (Opecode::CMP, Operand::IndirectIndex(IndexRegister::X)),
        (Opecode::NOP, Operand::Nope),
        (Opecode::NOP, Operand::Nope),
        (Opecode::CPY, Operand::ZeroPage),
        (Opecode::CMP, Operand::ZeroPage),
        (Opecode::DEC, Operand::ZeroPage),
        (Opecode::NOP, Operand::Nope),
        (Opecode::INY, Operand::Implied),
        (Opecode::CMP, Operand::Immediate),
        (Opecode::DEX, Operand::Implied),
        (Opecode::NOP, Operand::Nope),
        (Opecode::CPY, Operand::Absolute),
        (Opecode::CMP, Operand::Absolute),
        (Opecode::DEC, Operand::Absolute),
        (Opecode::NOP, Operand::Nope),
    ],
    /*d*/
    [
        (Opecode::BNE, Operand::Relative),
        (Opecode::CMP, Operand::IndirectIndex(IndexRegister::Y)),
        (Opecode::NOP, Operand::Nope),
        (Opecode::NOP, Operand::Nope),
        (Opecode::NOP, Operand::Nope),
        (Opecode::CMP, Operand::ZeroPageIndex(IndexRegister::X)),
        (Opecode::DEC, Operand::ZeroPageIndex(IndexRegister::X)),
        (Opecode::NOP, Operand::Nope),
        (Opecode::CLD, Operand::Implied),
        (Opecode::CMP, Operand::AbsoluteIndex(IndexRegister::Y)),
        (Opecode::NOP, Operand::Nope),
        (Opecode::NOP, Operand::Nope),
        (Opecode::NOP, Operand::Nope),
        (Opecode::CMP, Operand::AbsoluteIndex(IndexRegister::X)),
        (Opecode::DEC, Operand::AbsoluteIndex(IndexRegister::X)),
        (Opecode::NOP, Operand::Nope),
    ],
    /*e*/
    [
        (Opecode::CPX, Operand::Immediate),
        (Opecode::SBC, Operand::IndirectIndex(IndexRegister::X)),
        (Opecode::NOP, Operand::Nope),
        (Opecode::NOP, Operand::Nope),
        (Opecode::CPX, Operand::ZeroPage),
        (Opecode::SBC, Operand::ZeroPage),
        (Opecode::INC, Operand::ZeroPage),
        (Opecode::NOP, Operand::Nope),
        (Opecode::INX, Operand::Implied),
        (Opecode::SBC, Operand::Immediate),
        (Opecode::NOP, Operand::Implied),
        (Opecode::NOP, Operand::Nope),
        (Opecode::CPX, Operand::Absolute),
        (Opecode::SBC, Operand::Absolute),
        (Opecode::INC, Operand::Absolute),
        (Opecode::NOP, Operand::Nope),
    ],
    /*f*/
    [
        (Opecode::BEQ, Operand::Relative),
        (Opecode::SBC, Operand::IndirectIndex(IndexRegister::Y)),
        (Opecode::NOP, Operand::Nope),
        (Opecode::NOP, Operand::Nope),
        (Opecode::NOP, Operand::Nope),
        (Opecode::SBC, Operand::ZeroPageIndex(IndexRegister::X)),
        (Opecode::INC, Operand::ZeroPageIndex(IndexRegister::X)),
        (Opecode::NOP, Operand::Nope),
        (Opecode::SED, Operand::Implied),
        (Opecode::SBC, Operand::AbsoluteIndex(IndexRegister::Y)),
        (Opecode::NOP, Operand::Nope),
        (Opecode::NOP, Operand::Nope),
        (Opecode::NOP, Operand::Nope),
        (Opecode::SBC, Operand::AbsoluteIndex(IndexRegister::X)),
        (Opecode::INC, Operand::AbsoluteIndex(IndexRegister::X)),
        (Opecode::NOP, Operand::Nope),
    ],
];
